services:
  db:
    image: postgres:16-alpine
    container_name: task4_postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: task4_web_app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: